
package cn.com.itrus.raapi;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.8
 * 2014-11-27T15:03:58.099+08:00
 * Generated source version: 2.6.8
 */

@WebFault(name = "RaServiceUnavailable", targetNamespace = "http://service.ra.tca.topca.cn/")
public class RaServiceUnavailable_Exception extends Exception {
    
    private cn.com.itrus.raapi.RaServiceUnavailable raServiceUnavailable;

    public RaServiceUnavailable_Exception() {
        super();
    }
    
    public RaServiceUnavailable_Exception(String message) {
        super(message);
    }
    
    public RaServiceUnavailable_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public RaServiceUnavailable_Exception(String message, cn.com.itrus.raapi.RaServiceUnavailable raServiceUnavailable) {
        super(message);
        this.raServiceUnavailable = raServiceUnavailable;
    }

    public RaServiceUnavailable_Exception(String message, cn.com.itrus.raapi.RaServiceUnavailable raServiceUnavailable, Throwable cause) {
        super(message, cause);
        this.raServiceUnavailable = raServiceUnavailable;
    }

    public cn.com.itrus.raapi.RaServiceUnavailable getFaultInfo() {
        return this.raServiceUnavailable;
    }
}
