
package cn.com.itrus.raapi;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.6.8
 * 2014-11-27T15:03:58.025+08:00
 * Generated source version: 2.6.8
 * 
 */
public final class UserAPIServicePortType_UserAPIServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://service.ra.tca.topca.cn/", "UserAPIService");

    private UserAPIServicePortType_UserAPIServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = UserAPIService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        UserAPIService ss = new UserAPIService(wsdlURL, SERVICE_NAME);
        UserAPIServicePortType port = ss.getUserAPIServicePort();  
        
        {
        System.out.println("Invoking queryCertByCertId...");
        int _queryCertByCertId_certId = 0;
        java.lang.String _queryCertByCertId_accountHash = "";
        java.lang.String _queryCertByCertId_json = "";
        try {
            cn.com.itrus.raapi.QueryCertResult _queryCertByCertId__return = port.queryCertByCertId(_queryCertByCertId_certId, _queryCertByCertId_accountHash, _queryCertByCertId_json);
            System.out.println("queryCertByCertId.result=" + _queryCertByCertId__return);

        } catch (RaServiceUnavailable_Exception e) { 
            System.out.println("Expected exception: RaServiceUnavailable has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking downloadCRL...");
        java.lang.String _downloadCRL_accountHash = "";
        try {
            java.lang.String _downloadCRL__return = port.downloadCRL(_downloadCRL_accountHash);
            System.out.println("downloadCRL.result=" + _downloadCRL__return);

        } catch (RaServiceUnavailable_Exception e) { 
            System.out.println("Expected exception: RaServiceUnavailable has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking enrollCert...");
        cn.com.itrus.raapi.UserInfo _enrollCert_userInfo = null;
        java.lang.String _enrollCert_certReqBuf = "";
        java.lang.String _enrollCert_certReqChallenge = "";
        java.lang.String _enrollCert_accountHash = "";
        java.lang.String _enrollCert_json = "";
        try {
            port.enrollCert(_enrollCert_userInfo, _enrollCert_certReqBuf, _enrollCert_certReqChallenge, _enrollCert_accountHash, _enrollCert_json);

        } catch (RaServiceUnavailable_Exception e) { 
            System.out.println("Expected exception: RaServiceUnavailable has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking unsuspendCert...");
        java.lang.String _unsuspendCert_serialNumber = "";
        java.lang.String _unsuspendCert_accountHash = "";
        java.lang.String _unsuspendCert_json = "";
        try {
            port.unsuspendCert(_unsuspendCert_serialNumber, _unsuspendCert_accountHash, _unsuspendCert_json);

        } catch (RaServiceUnavailable_Exception e) { 
            System.out.println("Expected exception: RaServiceUnavailable has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking queryCerts...");
        cn.com.itrus.raapi.UserInfo _queryCerts_userInfo = null;
        cn.com.itrus.raapi.CertInfo _queryCerts_certInfo = null;
        int _queryCerts_pageIndex = 0;
        int _queryCerts_pageSize = 0;
        java.lang.String _queryCerts_sqlTemplateFileName = "";
        java.lang.String _queryCerts_nextResultTag = "";
        java.lang.String _queryCerts_totalTag = "";
        java.lang.String _queryCerts_accountHash = "";
        try {
            cn.com.itrus.raapi.QueryCertResult _queryCerts__return = port.queryCerts(_queryCerts_userInfo, _queryCerts_certInfo, _queryCerts_pageIndex, _queryCerts_pageSize, _queryCerts_sqlTemplateFileName, _queryCerts_nextResultTag, _queryCerts_totalTag, _queryCerts_accountHash);
            System.out.println("queryCerts.result=" + _queryCerts__return);

        } catch (RaServiceUnavailable_Exception e) { 
            System.out.println("Expected exception: RaServiceUnavailable has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking renewCertAA...");
        cn.com.itrus.raapi.UserInfo _renewCertAA_userInfo = null;
        cn.com.itrus.raapi.CertInfo _renewCertAA_origin = null;
        java.lang.String _renewCertAA_accountHash = "";
        java.lang.String _renewCertAA_aaCheckPoint = "";
        java.lang.String _renewCertAA_passCode = "";
        java.lang.String _renewCertAA_json = "";
        try {
            cn.com.itrus.raapi.CertInfo _renewCertAA__return = port.renewCertAA(_renewCertAA_userInfo, _renewCertAA_origin, _renewCertAA_accountHash, _renewCertAA_aaCheckPoint, _renewCertAA_passCode, _renewCertAA_json);
            System.out.println("renewCertAA.result=" + _renewCertAA__return);

        } catch (RaServiceUnavailable_Exception e) { 
            System.out.println("Expected exception: RaServiceUnavailable has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking downloadDeltaCRL...");
        java.lang.String _downloadDeltaCRL_accountHash = "";
        try {
            java.lang.String _downloadDeltaCRL__return = port.downloadDeltaCRL(_downloadDeltaCRL_accountHash);
            System.out.println("downloadDeltaCRL.result=" + _downloadDeltaCRL__return);

        } catch (RaServiceUnavailable_Exception e) { 
            System.out.println("Expected exception: RaServiceUnavailable has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking downloadCA...");
        java.lang.String _downloadCA_accountHash = "";
        try {
            java.lang.String _downloadCA__return = port.downloadCA(_downloadCA_accountHash);
            System.out.println("downloadCA.result=" + _downloadCA__return);

        } catch (RaServiceUnavailable_Exception e) { 
            System.out.println("Expected exception: RaServiceUnavailable has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking doScript...");
        java.lang.String _doScript_scriptName = "";
        java.lang.String _doScript_jsonMap = "";
        try {
            java.lang.String _doScript__return = port.doScript(_doScript_scriptName, _doScript_jsonMap);
            System.out.println("doScript.result=" + _doScript__return);

        } catch (RaServiceUnavailable_Exception e) { 
            System.out.println("Expected exception: RaServiceUnavailable has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking pickupCert...");
        java.lang.String _pickupCert_certPin = "";
        java.lang.String _pickupCert_certReqChallenge = "";
        java.lang.String _pickupCert_certReqBuf = "";
        java.lang.String _pickupCert_accountHash = "";
        java.lang.String _pickupCert_json = "";
        try {
            cn.com.itrus.raapi.CertInfo _pickupCert__return = port.pickupCert(_pickupCert_certPin, _pickupCert_certReqChallenge, _pickupCert_certReqBuf, _pickupCert_accountHash, _pickupCert_json);
            System.out.println("pickupCert.result=" + _pickupCert__return);

        } catch (RaServiceUnavailable_Exception e) { 
            System.out.println("Expected exception: RaServiceUnavailable has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking queryCertBySerialNumber...");
        java.lang.String _queryCertBySerialNumber_serialNumber = "";
        java.lang.String _queryCertBySerialNumber_accountHash = "";
        java.lang.String _queryCertBySerialNumber_json = "";
        try {
            cn.com.itrus.raapi.QueryCertResult _queryCertBySerialNumber__return = port.queryCertBySerialNumber(_queryCertBySerialNumber_serialNumber, _queryCertBySerialNumber_accountHash, _queryCertBySerialNumber_json);
            System.out.println("queryCertBySerialNumber.result=" + _queryCertBySerialNumber__return);

        } catch (RaServiceUnavailable_Exception e) { 
            System.out.println("Expected exception: RaServiceUnavailable has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking synchroTemplate...");
        java.lang.String _synchroTemplate_accountHash = "";
        try {
            cn.com.itrus.raapi.AccountConfigResult _synchroTemplate__return = port.synchroTemplate(_synchroTemplate_accountHash);
            System.out.println("synchroTemplate.result=" + _synchroTemplate__return);

        } catch (RaServiceUnavailable_Exception e) { 
            System.out.println("Expected exception: RaServiceUnavailable has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking renewCert...");
        cn.com.itrus.raapi.UserInfo _renewCert_userInfo = null;
        cn.com.itrus.raapi.CertInfo _renewCert_origin = null;
        java.lang.String _renewCert_accountHash = "";
        java.lang.String _renewCert_json = "";
        try {
            port.renewCert(_renewCert_userInfo, _renewCert_origin, _renewCert_accountHash, _renewCert_json);

        } catch (RaServiceUnavailable_Exception e) { 
            System.out.println("Expected exception: RaServiceUnavailable has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking revokeCert...");
        java.lang.String _revokeCert_serialNumber = "";
        java.lang.String _revokeCert_certReqChallenge = "";
        java.lang.String _revokeCert_certRevokeReason = "";
        java.lang.String _revokeCert_accountHash = "";
        java.lang.String _revokeCert_json = "";
        try {
            port.revokeCert(_revokeCert_serialNumber, _revokeCert_certReqChallenge, _revokeCert_certRevokeReason, _revokeCert_accountHash, _revokeCert_json);

        } catch (RaServiceUnavailable_Exception e) { 
            System.out.println("Expected exception: RaServiceUnavailable has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking suspendCert...");
        java.lang.String _suspendCert_serialNumber = "";
        java.lang.String _suspendCert_accountHash = "";
        java.lang.String _suspendCert_json = "";
        try {
            port.suspendCert(_suspendCert_serialNumber, _suspendCert_accountHash, _suspendCert_json);

        } catch (RaServiceUnavailable_Exception e) { 
            System.out.println("Expected exception: RaServiceUnavailable has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking enrollCertAA...");
        cn.com.itrus.raapi.UserInfo _enrollCertAA_userInfo = null;
        java.lang.String _enrollCertAA_certReqBuf = "";
        java.lang.String _enrollCertAA_accountHash = "";
        java.lang.String _enrollCertAA_aaCheckPoint = "";
        java.lang.String _enrollCertAA_passCode = "";
        java.lang.String _enrollCertAA_json = "";
        try {
            cn.com.itrus.raapi.CertInfo _enrollCertAA__return = port.enrollCertAA(_enrollCertAA_userInfo, _enrollCertAA_certReqBuf, _enrollCertAA_accountHash, _enrollCertAA_aaCheckPoint, _enrollCertAA_passCode, _enrollCertAA_json);
            System.out.println("enrollCertAA.result=" + _enrollCertAA__return);

        } catch (RaServiceUnavailable_Exception e) { 
            System.out.println("Expected exception: RaServiceUnavailable has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
